server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /auth {
        proxy_pass http://backend:3000;
        proxy_set_header Host $host;
    }

    location /tasks {
        proxy_pass http://backend:3000;
        proxy_set_header Host $host;
    }
}
